#define MAJOR 2
#define MINOR 5
#define PATCH 0
#define BUILD 348


// #define VERSION MACROS
#define VERSION MAJOR.MINOR
#define VERSION_AR MAJOR,MINOR,PATCH
#define VERSION_STR MAJOR##.##MINOR##.##PATCH
